swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account Module
      summary: Get user accounts
      description: Retrieve the list of bank accounts associated with the logged-in user.
      produces:
        - application/json
      responses:
        "200":
          description: List of user accounts retrieved successfully with basic informations
          schema:
            type: array
            items:
              $ref: "#/definitions/Account"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token invalid or missing
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get account transactions
      description: Retrieve the list of transactions for a specific account.
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: The ID of the account
      produces:
        - application/json
      responses:
        "200":
          description: List of transactions retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token invalid or missing
        "404":
          description: Account not found
        "500":
          description: Internal Server Error

  /user/accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction details
      description: Retrieve the details of a specific transaction (type, category, notes).
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: The ID of the account
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetails"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token invalid or missing
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

  /accounts/{accountId}/transactions/{transactionId}/details:
    post:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Add transaction details
      description: Add additional details (category, note) to a specific transaction.
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: The ID of the account
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction
        - in: body
          name: body
          description: Details to add
          required: true
          schema:
            $ref: "#/definitions/TransactionDetails"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details added successfully
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token invalid or missing
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Modify transaction details
      description: Modify existing details (category, note) of a specific transaction.
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: The ID of the account
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction
        - in: body
          name: body
          description: Details to modify
          required: true
          schema:
            $ref: "#/definitions/TransactionDetails"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details modified successfully
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token invalid or missing
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction details
      description: Delete specific details (category, note) of a specific transaction.
      parameters:
        - in: path
          name: accountId
          required: true
          type: string
          description: The ID of the account
        - in: path
          name: transactionId
          required: true
          type: string
          description: The ID of the transaction
        - in: body
          name: body
          description: Details to delete
          required: true
          schema:
            $ref: "#/definitions/TransactionDetails"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details deleted successfully
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized - Token invalid or missing
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  Account:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      balance:
        type: number
      type:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date-time
      amount:
        type: number
      type:
        type: string
      description:
        type: string

  TransactionDetails:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
